formatter: markdown table
output:
  file: README.md
  mode: inject
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: false
  default: true
  description: true
  escape: true
  hide: []
  html: false
  indent: 2
  required: true
  sensitive: true
  type: true
